name = "RepositoryMigrationKit"
uuid = "dd57726b-2b50-4bdf-a3b0-28dd47b61508"
authors = ["singularitti <singularitti@outlook.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
